version: '2'
services:
    web:
        build:
            context: ./app
        ports:
            - "5000:5000"
        links:
            - redisdb
        environment:
            - REDIS_HOST=redisdb
            - REDIS_PORT=6379
    redisdb:
        image: redis
        volumes:
            - redis_data:/data
volumes:
    redis_data:
