version: '2'
services:
    web:
        build:
            context: ./app
        ports:
            - "5000:5000"
        depends_on:
            - redisdb
    redisdb:
        image: redis
        volumes:
            - redis_data:/data
volumes:
    redis_data:
